development:
  adapter: mysql
  encoding: utf8
  database: gamelog_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: gamelog_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: gamelog_production
  pool: 5
  username: root
  password:
  host: localhost
