development:
  adapter: mysql
  encoding: utf8
  database: rpgtracker_development
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql
  encoding: utf8
  database: rpgtracker_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: rpgtracker_production
  pool: 5
  username: root
  password:
  host: localhost

cucumber:
  <<: *test